workflows:
  pr_workflow:
    name: Run on Pull Request
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
    scripts:
      - name: Get dependencies
        script: |
          flutter packages pub get