workflows:
  check_formatting:
    name: Check Code Formatting 
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
        - pattern: '*'
          include: true
    scripts:
      - name: Check Code Formatting
        script: |
          dart format --set-exit-if-changed lib/